main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: /publications/
    weight: 20
  - name: CV
    url: /experience/
    weight: 25
  - name: Collaborators
    url: /collaborators/
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
